language: perl
sudo: false
perl:
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"

install: cpanm --quiet --installdeps --with-develop --with-recommends --with-suggests --notest .
